Update main_webappprod.yml

diff --git a/.github/workflows/main_webappprod.yml b/.github/workflows/main_webappprod.yml
--- a/.github/workflows/main_webappprod.yml
+++ b/.github/workflows/main_webappprod.yml
@@ -84,3 +84,14 @@ jobs:
           run: |
            echo "Deployment to Azure Web App successful"
 
+      - name: Check deployment status
+        run: |
+          status=$(echo "${{ steps.deploy.outputs.deployment_status }}" | tr '[:upper:]' '[:lower:]')
+          if [ "$status" != "success" ]; then
+            echo "Deployment failed with status: $status"
+            exit 1
+          fi
+          echo "Deployment successful!"
+
+          
+
